version: "3"
services:
  app:
    container_name: myapp
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
      - /home/app/node_modules
  redis_db:
    image: "redis:alpine"
    ports:
      - "6379:6379"
